Project aware {
    database_type: 'PostgreSQL'
    Note: 'Aware is an application designed to help users gain awareness of how they spend their time.'

}

TablePartial id {
    id int [primary key]
}

TablePartial time_bounds {
    start integer [note: "Unix epoch in UTC"]
    stop integer [note: "Unix epoch in UTC"]
}

TablePartial name_info {
    name varchar
    description varchar
}

Table aware.labels {
    ~id
    ~name_info
}

Table aware.activity_types {
    ~id
    ~name_info
    ~time_bounds
}

Table aware.activity_types_labels {
    activity_type_id integer [ref: > aware.activity_types.id]
    label_id integer [ref: > aware.labels.id]
    indexes {
        (activity_type_id, label_id) [pk]
    }
}

Table aware.activities {
    ~id
    ~time_bounds
    activity_type_id integer [ref: > aware.activity_types.id]
}
